### ISSUE TITLE
По числам сложно понять, лучше хранить строки

### ISSUE THREAD

**Issue by coursar** [sergey-lb/corporate-emails#2]
https://github.com/sergey-lb/corporate-emails/blob/ddd4a9625def57bddd65add18a8f7a204115245a/requests.sql#L20

Не всегда это верно, в данном случае увеличит читаемость + вы сможете поставить CHECK на то, что значение только эти три

**Comment by sergey-lb** [comment]
Исправлено в b91224c366ad99b12577d7657b341c9403dcb58d . В каких случаях лучше числа использовать, кроме когда варианта всего два?

**Comment by coursar** [comment]
Когда два - их точно будет два: True/False

**Comment by coursar** [comment]
Когда это числовое значение - тогда числа
